web:
  image: leonhart/railstutorial
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - mysql
    - redis
mysql:
  image: mysql
  volumes:
    - mysql_data:/var/lib/mysql
  environment: 
    MYSQL_ROOT_PASSWORD: password  
    MYSQL_DATABASE: app_development  
  ports:
    - "3306:3306"
redis:
  image: redis
  ports:
    - "6379:6379"
